### PR TITLE
Introduce some project structure

### PR DESCRIPTION
**Pull request by devrnt**
In general some project setup & strucutre. I don't know how usefull this will be but this PR includes following:

### Changes
* Introduce an overall more maintainable project strucutre ("future proof")
* Introduce config files
* Introduce multi staged docker builds

### TODO
* Introduce logger 
* Introduce source map support for stack traces
* Introduce linter and formatter
* Unify event names (socket.io recomments has to convention to name their events as `<scope>:<action>` E.g. `user:create`)
* Clearify README (how to run project on host or in container...)

### CODE REVIEW

**Comment by BramDC3** [comment]
Thanks bud :D

I've been neglecting the server, setting up the two smartphone apps seemed more important. I was planning on creating a proper architecture as soon as I've defined all socket.io actions that'll be needed for the first prototype. This seems like a good start.

**Comment by devrnt** [comment]
Do whatever works best with it :) 

Btw small question: I saw a few repo's related to smart duel, have you thought about creating a Github organisation?

**Comment by BramDC3** [comment]
I have, but I'm hesitating because I'm considering moving everything to GitLab

**Comment by BramDC3** [comment]
Merged to develop instead

**Pull request closed without merging**
